### ISSUE TITLE
Lepszy pomysł na 8 sąsiadów

### ISSUE THREAD

**Issue by MarcinCiura** [MuFFes/pacman#1]
Zakodować bieżący stan 8 sąsiadów w 8-znakowym napisie złożonym z `'0'` i `'1'` (albo `'X'` i `' '`, albo co Pan uzna za najbardziej sugestywne). Mieć przygotowaną stałą listę regexpów:
```python
RULES = [
    re.compile('^0.0.1.1.$'),
    re.compile('^1.1.0.0.$'),
    itd.
```
i zrobić mini-metodę z taką pętlą:
```python
for i, rule in enumerate(RULES):
    if rule.match(neighbors):
        return i
return -1  # Albo None.
```
(Wolę takie pętle wrzucać do osobnych funkcji niż używać `else` do `for`, bo szczerze mówiąc nie pamiętam, kiedy takie `else` się wykonuje.)
Kodowanie stanu też stablicować: mieć stałą
```python
NEIGHBOR_COORDINATES = [(-1, 0), (+1, 0), itd.
```
(Lubię pisać `+1` zamiast `1`, jeśli w okolicy jest `-1` — dla czytelności.)

**Comment by najbardziej** [comment]
Lista regexpów wyszła dość długa, ale chyba nie dam rady jej bardziej zredukować. 
Z racji wykorzystywania generatora nie tworzyłem dodatkowych metod.
Proszę o informację, czy kod jest wystarczająco dobry, czy też powinienem coś zmodyfikować :)
[Link do commita naprawiającego problem](https://github.com/MuFFes/pacman/commit/25abfadcf57c868edb80a88c66286d7d731eef89)

**Comment by MarcinCiura** [comment]
Jest OK. Opcjonalnie może Pan połączyć regexpy:
```python
'^(...11.10)|(...)|(...)|(...)$',
itd.
```
i zwracać indeks reguły.

**Comment by najbardziej** [comment]
[Poprawione - commit](https://github.com/MuFFes/pacman/commit/478a379d58fad9c98c3f65da2cbc3c3e234e01de)
zamykam 'issue'

**Comment by MarcinCiura** [comment]
Super. Mimo to mam dwa komentarze, bo widzę, że Panu zależy na jakości.

1. Przy najbliższym commicie proszę rozważyć tę uwagę: zamiast wrzucać te dwie nowe stałe w `constants.py` wg klucza "to są stałe", chyba lepiej by było je trzymać w ich module. Primo nigdy się poza nim nie przydadzą, secundo każda ich zmiana rozwali program w odróżnieniu od zmian kolorów, prędkości, nazw plików graficznych (połączonych z utworzeniem tych plików) itp. stałych z `constants.py`. Tym samym krytycznym okiem proszę się przyglądać wszystkim stałym w przyszłości.

2. `re.match(wzorzec, napis)` zasadniczo nie jest złe, ale:
* próbuje rekompilować `wzorzec` przy każdym wywołaniu, co jest nieprzyjemne o tyle, że jest wywoływane w wewnętrznej pętli;
* wprawdzie nie będzie go rekompilować, bo `re` ma w środku — właśnie dla nieuważnych programistów — cache, które odwzorowuje bodajże do 100 ostatnio używanych wzorców na skompilowane regexpy, ale to jest szczegół implementacyjny, którego chyba nie gwarantuje dokumentacja;
* użycie `re.compile()` raz a dobrze jest pozbawione powyższych mankamentów.

W zależności od zapatrywań można zredukować liczbę kopiowanych wywołań `re.compile()` np. tak:
```python
WALL_RULES = [re.compile(x) for x in """
        ^(...)|(...)|(...)|(...)$
        ^(...)|(...)|(...)$
    """.split()]
```
albo i nie.
