### ISSUE TITLE
Uwagi

### ISSUE THREAD

**Issue by MarcinCiura** [MuFFes/pacman#2]
Bardzo mi się podobało dzisiejsze demo projektu. Tych parę uwag dotyczy stylu.

1. W `Barrier` zrobić metodę do rysowania danym kolorem i przerobić `draw()` i `clear()` na jednolinijkowce.
2. Z [tego](https://github.com/MuFFes/pacman/blob/c40c4ad5be15cae10a361dfcd913baec9eee7c3f/game_files/Player.py#L65) powtarzającego się fragmentu zrobić metodę czy coś.
3. Przypominam o zmianie [tych akrobacji](https://github.com/MuFFes/pacman/blob/c40c4ad5be15cae10a361dfcd913baec9eee7c3f/game_files/constants.py#L106) na użycie `bisect`.
4. Nie rozumiem wyrazu `ELROY`.
5. W razie trudności z 8 sąsiadami z drugiego *Issue* proszę o kontakt.

**Comment by MarcinCiura** [comment]
W razie, gdyby [Pańska zagłada enumów](https://github.com/MuFFes/pacman/commit/c40c4ad5be15cae10a361dfcd913baec9eee7c3f) wynikała ze złego wyjaśnienia prawa Demeter przeze mnie, [poprawiłem](https://github.com/MarcinCiura/pk-jezyki-symboliczne/commit/76041996292f2d5024b15602eb6024d5bf5217d8).

**Comment by najbardziej** [comment]
Nie, stwierdziłem że skrócenie linii o te naście znaków poprawi czytelność, zwłaszcza jeśli dzięki temu mogę w kilku miejscach nie dzielić linii przy limicie 80 znaków

**Comment by najbardziej** [comment]
1. [Zrobione](https://github.com/MuFFes/pacman/blob/7f141196e2874bfda49e3c2bef1904c304540e18/game_files/barrier.py#L18)
2. [Zrobione](https://github.com/MuFFes/pacman/blob/7f141196e2874bfda49e3c2bef1904c304540e18/game_files/characters.py#L8)
3. [Zrobione](https://github.com/MuFFes/pacman/blob/7f141196e2874bfda49e3c2bef1904c304540e18/game_files/constants.py#L112)
4. Jest to specjalny tryb w który wchodzi czerwony duszek - przyspiesza, gdy na planszy zostaje odpowiednia liczba kropek do zjedzenia. Na pewno wrzucę to jeszcze do jakiegoś docstringa.
5. Zrobione

Powoli przywracam porządek w działaniu kodu, ale nie wiem czy jestem w stanie zdążyć jeszcze przed sesją.

Kolejna rzecz jaką planuję zmienić jest poprawienie działania - i jakości kodu [metody move w klasie Ghost](https://github.com/MuFFes/pacman/blob/63e1cb8ff39094fc619083b255da5091552b2771/game_files/characters.py#L112)

Gdyby miał Pan kolejne uwagi, z chęcią uwzględnię zmiany w kodzie.

**Comment by MarcinCiura** [comment]
Dziękuję za wiadomość. Nie mam więcej uwag do kodu. Proszę zrobić jakiekolwiek testy i będzie po wszystkim.

**Comment by najbardziej** [comment]
- [Usunąłem znaczną część referencji do obiektu game](https://github.com/MuFFes/pacman/commit/68594aee5747890523160d0ecc326ea268054c76)
- Naprawiłem kilka niewielkich bugów
- [Poprawiłem działanie i kod metody move w klasie Ghost](https://github.com/MuFFes/pacman/commit/8b277d4afa6282401c91ea0ed478c2433ad5ead8)
- [Dodałem plik pylintrc - zmiany w komentarzu na początku pliku](https://github.com/MuFFes/pacman/blob/master/pylintrc)
- [Dodałem docstringi](https://github.com/MuFFes/pacman/commit/92867eb2dd70a95a3f44390d2ad837ece43a1e49)
- [Dodałem testy jednostkowe modułu Map](https://github.com/MuFFes/pacman/blob/master/game_files/map_test.py)

**Comment by MarcinCiura** [comment]
Świetnie, LGTM. Gratuluję, jest Pan dwudziesty piąty. Nie znałem `parameterized`.

W wolnej chwili w testach: zmienić `self.MAP` na `self.map`; skoro robienie `self.map` wymaga czytania z pliku, to już nie jest takie lekkie, żeby je zostawiać w `setUp()`, więc może Pan użyć `.setUpClass()`.

Dodatkowa prośba: jeśli nikt tego przed Panem nie zrobi, proszę ogłosić konsultacje w niedzielę o 20:30 i w poniedziałek o 12:00 pod standardowym linkiem. Dziękuję!

**Comment by najbardziej** [comment]
Dziękuję. Wprowadzę zmiany i zamykam issue
